### ISSUE TITLE
When to use Redux

### ISSUE THREAD

**Issue by Prefinem** [jsmapr1/kc-react-meetup#8]
I would like to talk about when the right time to use redux is and how to manage apps with a lot of state.

Topics covered:
* Redux
* Sagas
* Selectors
* Module Structure
* Boilerplate for modules
* Large Stage Management
* Componentization of View Components and Redux

**Comment by Prefinem** [comment]
@jsmapr1 FYI, it's not possible to assign tickets we create or to label them.

Thanks

**Comment by jsmapr1** [comment]
Hmm. I'll check the permissions. Thanks for the suggestions
